### ISSUE TITLE
参加規約

### ISSUE THREAD

**Issue by kikuchy** [FlutterKaigi/flutterkaigi#3]
CfP提出時に同意してもらう参加規約が必要。

# 入れたほうが良さそうな項目

* 採択/非採択に関わらず、セッションタイトル、応募者名は公開される
* 報酬などは発生しない
* 投稿件数の上限
	* Droidkaigiは3件まで。4件以上は失格
* 発表は動画に残る
	* スライドを画面共有して発表する方式を想定している
	* 資料は表示する必要がある
	* 顔出しする必要はない
	* アバターや合成音声などを使用する場合、発表者の責任で権利関係をクリアにすること
* グループで発表する際は全員の名前を記載する
* 免責事項
	* 突然中止したらごめんね

# 入れる？入れない？

* 未成年者は保護者の同意が必要

**Comment by kikuchy** [comment]
参考

* https://sessionize.com/droidkaigi2021/
* https://techbookfest.org/event/tbf11#requirements
* http://www.designit.jp/archives/terms/

**Comment by kikuchy** [comment]
どちらかと言えば募集要項に記載する内容だった…
参加規約と募集要項は別に考えたほうがいいかもしれませんね…

**Comment by mightyfrog** [comment]
配信動画のアーカイブ配信の同意。
